---
Name: idsk-elemental-config
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'tjbw/silverstripe-idsk-elemental:client/dist/styles/bundle.css'
---
Name: modules-idsk-elemental-config
Before: modules-other
---
SilverStripe\Core\Manifest\ModuleManifest:
  module_priority:
    - tjbw/silverstripe-idsk-elemental
---
Name: idsk-elemental-model-userforms-config
Only:
  moduleexists: silverstripe/userforms
---
SilverStripe\UserForms\Model\UserDefinedForm:
  upgrade_on_build: false
---
Name: idsk-elemental-model-grid-config
Only:
  moduleexists: wedevelopnl/silverstripe-elemental-grid
---
SilverStripe\Core\Injector\Injector:
  WeDevelop\ElementalGrid\Extensions\ElementalAreaExtension:
    class: TJBW\IdSkElemental\Extensions\ElementalAreaExtension
